// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwn6yla2kUvXwseMNIl2V4GFBXk9nbQJs',
    appId: '1:333972031891:web:e066a843c1eeb332a38066',
    messagingSenderId: '333972031891',
    projectId: 'tutor2-firebase',
    authDomain: 'tutor2-firebase.firebaseapp.com',
    storageBucket: 'tutor2-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrDPSU9tILuVAq2iGiDUCGH76DdxmDdkQ',
    appId: '1:333972031891:android:f75b3acc997c1429a38066',
    messagingSenderId: '333972031891',
    projectId: 'tutor2-firebase',
    storageBucket: 'tutor2-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0NvLp0kTPeKqiatsEX5ddAW_ws-yKkUg',
    appId: '1:333972031891:ios:fb8dec114f650304a38066',
    messagingSenderId: '333972031891',
    projectId: 'tutor2-firebase',
    storageBucket: 'tutor2-firebase.appspot.com',
    iosBundleId: 'com.example.tutorFirebase1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0NvLp0kTPeKqiatsEX5ddAW_ws-yKkUg',
    appId: '1:333972031891:ios:f3b045dc8117419aa38066',
    messagingSenderId: '333972031891',
    projectId: 'tutor2-firebase',
    storageBucket: 'tutor2-firebase.appspot.com',
    iosBundleId: 'com.example.tutorFirebase1.RunnerTests',
  );
}
